# Generated by Django 4.1.3 on 2022-11-21 20:21

from django.db import migrations, models
import django.db.models.aggregates
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City_Details',
            fields=[
                ('Dept_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('City_name', models.CharField(max_length=100)),
                ('No_of_Laborers', models.IntegerField()),
                ('No_of_Supervisor', models.IntegerField()),
            ],
            options={
                'db_table': 'City details',
            },
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('Labor_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Rating', models.FloatField()),
                ('Name', models.CharField(max_length=500)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Bigender', 'Bigender')], max_length=20)),
                ('Work', models.CharField(choices=[('Professionals', 'Professionals'), ('Legislators', 'Legislators'), ('Senior officials and managers', 'Senior officials and managers'), ('Technicians and associate professionals', 'Technicians and associate professionals'), ('Elementary occupations', 'Elementary occupations'), ('Service workers', 'Service workers'), ('Shop and market sales workers', 'Shop and market sales workers'), ('Skilled agricultural and fishery workers', 'Skilled agricultural and fishery workers'), ('Craft and related trades workers', 'Craft and related trades workers'), ('Plant and machine operators and assemblers', 'Plant and machine operators and assemblers'), ('Clerks', 'Clerks'), ('Other', 'Other')], max_length=500)),
                ('Work_type', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly')], default='Daily', max_length=25)),
                ('City_ID', models.ForeignKey(on_delete=django.db.models.aggregates.Aggregate, to='labor_register.city_details')),
            ],
            options={
                'db_table': 'Labor',
            },
        ),
        migrations.CreateModel(
            name='Municipal_Department',
            fields=[
                ('City_ID', models.IntegerField()),
                ('Dept_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Overall_rating', models.FloatField()),
                ('Total_expense', models.IntegerField()),
                ('UPI_ID_payer', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Municipal Department',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('Supervisor_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Rating', models.FloatField()),
                ('No_of_laborers', models.IntegerField()),
            ],
            options={
                'db_table': 'Supervisor',
            },
        ),
        migrations.CreateModel(
            name='Labor_Personal_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PinCode', models.IntegerField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Bigender', 'Bigender')], max_length=20)),
                ('Date_of_Birth', models.DateTimeField()),
                ('Name', models.CharField(max_length=500)),
                ('Community', models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=10)),
                ('City_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='labor_register.city_details')),
                ('Labor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_register.labor')),
            ],
            options={
                'db_table': 'Labor_Personal_Details',
            },
        ),
        migrations.AddField(
            model_name='labor',
            name='Supervisor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_register.supervisor'),
        ),
        migrations.AddField(
            model_name='city_details',
            name='City_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_register.municipal_department'),
        ),
    ]
